### PR TITLE
Drastically improve user experience on XTEA tool, increasing conversion rates by at least 500%

### PR DESCRIPTION
**Pull request by atampy25**
The old user interface was an abomination, causing many to turn away immediately upon seeing it. The new, superior interface is far better, increasing conversion rates (where a conversion is someone patching their packagedefinition or thumbs.dat) by up to 7000%. This masterful reimagining of the XTEA user interface is achieved through the following steps (numbered for clarity):

1. Remove terrible image with incredibly low resolution (123x40????)
2. Add new and good image
3. Find where to change styling (apparently the xtea image is a component for some reason)
3. Change styling because for some reason the website doesn't deal with it automatically (AAAAAAAAAAAA)

### CODE REVIEW

**Comment by acikek** [comment]
:regional_indicator_a:

**Comment by atampy25** [comment]
Not even a "LGTM"? Sad.

Very sad.

Crying my eyes out rn.

**Comment by RDIL** [comment]
It's a component because it allows for better code splitting.

**Comment by atampy25** [comment]
but it's three lines
```html
<div id="xtealogo">
    <img className="xtealogo" src="/xtea.png" alt="XTEA logo." />
</div>
```

why would you need to split that

**Comment by RDIL** [comment]
The image itself is a decent size, so lazy loading it is more efficient.  The rest of the page can load first, which stops the image from blocking the first paint.

**Pull request merged**
